<?php 
	// connection settings 
	DEFINE('MERCHANT_ID', ''); 
	DEFINE('ACCESS_KEY', ''); 
	DEFINE('ACCESS_KEY_REF', ''); 
	DEFINE('PROXY_HOST', ''); 
	DEFINE('PROXY_PORT', ''); 
	DEFINE('PROXY_LOGIN', ''); 
	DEFINE('PROXY_PASSWORD', ''); 
	DEFINE('ENVIRONMENT', 'HOMO'); 

	// web services settings 
	DEFINE( 'WS_VERSION', '');
	DEFINE( 'PAYMENT_CURRENCY', '978');
	DEFINE( 'ORDER_CURRENCY', '978');
	DEFINE( 'SECURITY_MODE', '');
	DEFINE( 'LANGUAGE_CODE', '');
	DEFINE( 'PAYMENT_ACTION', '101');
	DEFINE( 'PAYMENT_MODE', 'CPT');
	DEFINE( 'CANCEL_URL', '');
	DEFINE( 'NOTIFICATION_URL','');
	DEFINE( 'RETURN_URL', '');
	DEFINE( 'CUSTOM_PAYMENT_TEMPLATE_URL', '');
	DEFINE( 'CUSTOM_PAYMENT_PAGE_CODE', '');
	DEFINE( 'CONTRACT_NUMBER', 'CB');
	DEFINE( 'CONTRACT_NUMBER_LIST', '');
	DEFINE( 'SECOND_CONTRACT_NUMBER_LIST', '');

	// demo settings 
	DEFINE( 'KIT_ROOT', 'http://127.0.0.1/KIT_PHP/PHP/');
?> 
